swagger: "2.0"
info:
  title: 띵스플로우 과제 API Docs
  version: 0.0.1
host: localhost:7300
basePath: "/api/v1"
schemes:
- http
- https

tags:
- name: user
  description: 사용자에 관한 모든것
- name: heart
  description: 마이페이지( 사용자 정보 수정 )

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
paths:
  $ref: './path/index.yaml'
definitions:
  $ref: './path/definition.yaml'


